### PR TITLE
Add decorator for custom roles

### LINKED ISSUE #2: Decorator for a custom role
Currently on Flask we provide decorators for restricting the access to logged users and for users with the admin role. 
A decorator that limits access based on a custom role would provide flexibility to differentiate user groups based on their roles.

### PR DESCRIPTION
**Pull request by pablo-de-andres**

### CODE REVIEW

**Comment by pablo-de-andres** [comment]
Are you familiar with the [error](https://github.com/materials-marketplace/shieldapi/actions/runs/4795738610/jobs/8530678440?pr=3#step:5:219), @MBueschelberger? I am not 100% it might not be an issue with the tests.

**Comment by MBueschelberger** [comment]
> Are you familiar with the [error](https://github.com/materials-marketplace/shieldapi/actions/runs/4795738610/jobs/8530678440?pr=3#step:5:219), @MBueschelberger? I am not 100% it might not be an issue with the tests.

Seems to be a problem with the Keycloak-mock for the pytests. Probably because the mock directly returns a dict and not a request-object. I will look tomorrow into it.

**Comment by MBueschelberger** [comment]
Can reproduce, will have a look this afternoon.

**Review by MBueschelberger — APPROVED** [review]
Pytest fails were solved by fixing the keycloak mock for the `_check_active_token`-function.

**Pull request merged**
